# Generated by Django 3.0.4 on 2020-04-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='user_bio',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='usertype',
            name='user_photo',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
