# Generated by Django 3.0.4 on 2020-04-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200413_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='user_photo',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Man_silhouette.svg/200px-Man_silhouette.svg.png', max_length=2000),
        ),
    ]
