# Generated by Django 3.0.4 on 2020-04-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200413_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='user_bio',
            field=models.TextField(default='Здесь еще ничего нет! Расскажите о себе'),
        ),
    ]
